name: Release

# on: [pull_request]

on:
  workflow_dispatch:
    inputs:
      dryRun:
        description: "Do a dry run to preview instead of a real release"
        required: true
        default: "true"

jobs:
  authorize:
    name: Run tests
    runs-on: macos-latest
    steps:
      - name: ${{ github.actor }} permission check to do a release
        uses: octokit/request-action@v2.0.0
        with:
          route: GET /repos/:repository/collaborators/${{ github.actor }}
          repository: ${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run tests
        run: |
          swift test -c release -Xswiftc -enable-testing

  release:
    name: Release
    runs-on: macos-latest
    needs: [Run tests]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # - name: iOS Tests
      #   run: |
      #     xcodebuild test \
      #       -project Dashcam Viewer for Tesla.xcodeproj \
      #       -scheme TeslaTests \
      #       -sdk iphonesimulator \
      #       -destination 'platform=iOS Simulator,name=iPhone 11,OS=14.3'

      # - name: macOS Tests @TODO Fix flaky macOS tests and re-enable
      #   run: |
      #     xcodebuild \
      #       -workspace Dashcam Viewer for Tesla.xcodeproj \
      #       -scheme TeslaTests \
      #       -sdk macosx \
      #       -destination 'platform=macosx' \
      #       test

      # - name: Install appledoc binary
      #   run: |
      #     git clone git://github.com/tomaz/appledoc.git
      #     cd appledoc/
      #     sudo sh install-appledoc.sh
      #     cd ../
      #     rm -rf appledoc/

      - name: Semantic Release --dry-run
        if: ${{ github.event.inputs.dryRun == 'true'}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_AUTHOR_NAME: nscabezon@github-hook
          GIT_AUTHOR_EMAIL: nscabezon@gmail.com
          GIT_COMMITTER_NAME: nscabezon@github-hook
          GIT_COMMITTER_EMAIL: nscabezon@gmail.com
        run: |
          npx \
          -p lodash \
          -p semantic-release@17 \
          -p @semantic-release/changelog@5 \
          -p @semantic-release/git@9 \
          -p @google/semantic-release-replace-plugin@1 \
          -p @semantic-release/exec@5 \
          semantic-release --dry-run

      - name: Semantic Release
        if: ${{ github.event.inputs.dryRun == 'false'}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_AUTHOR_NAME: nscabezon@github-hook
          GIT_AUTHOR_EMAIL: nscabezon@gmail.com
          GIT_COMMITTER_NAME: nscabezon@github-hook
          GIT_COMMITTER_EMAIL: nscabezon@gmail.com
        run: |
          npx \
          -p lodash \
          -p semantic-release@17 \
          -p @semantic-release/changelog@5 \
          -p @semantic-release/git@9 \
          -p @google/semantic-release-replace-plugin@1 \
          -p @semantic-release/exec@5 \
          semantic-release
