name: Test

on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: macos-10.15
    strategy:
      matrix:
        ruby-version: ["2.7.x"]
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
          
      - name: Enable SSH
        run: |
          for ip in $(dig @8.8.8.8 github.com +short); do ssh-keyscan github.com,$ip; ssh-keyscan $ip; done 2>/dev/null >> ~/.ssh/known_hosts
          
      - name: Setup SSH Keys and known_hosts
        env:
            SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
            ssh-agent -a $SSH_AUTH_SOCK > /dev/null
            
      - name: Add CI SSH Key
        run: |
            ssh-add - <<< "${{ secrets.SSH_KEY }}"

      - name: Set Xcode 12
        run: |
          sudo xcode-select -switch /Applications/Xcode_12.app

      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}

      - name: Run tests
        run: |
          swift test -c release -Xswiftc -enable-testing